import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const phrasalVerbsData = [
  { verb: 'take', particle: 'off', meaningJa: '離陸する、脱ぐ', exampleSentence: 'The plane will take off soon.' },
  { verb: 'take', particle: 'on', meaningJa: '引き受ける、雇う', exampleSentence: 'He decided to take on new tasks.' },
  { verb: 'take', particle: 'up', meaningJa: '始める、占める', exampleSentence: 'She took up yoga last week.' },
  { verb: 'take', particle: 'over', meaningJa: '引き継ぐ、乗っ取る', exampleSentence: 'She will take over the project tomorrow.' },
  { verb: 'take', particle: 'in', meaningJa: '取り込む、だます', exampleSentence: 'I was taken in by his lies.' },
  { verb: 'take', particle: 'out', meaningJa: '連れ出す、取り出す', exampleSentence: 'He took me out for dinner.' },
  { verb: 'take', particle: 'after', meaningJa: '似ている', exampleSentence: 'She takes after her mother.' },
  { verb: 'take', particle: 'back', meaningJa: '撤回する、思い出す', exampleSentence: 'I take back what I said.' },
  { verb: 'get', particle: 'on', meaningJa: '乗る、仲良くやっていく', exampleSentence: 'Get on the bus before it leaves.' },
  { verb: 'get', particle: 'off', meaningJa: '降車する', exampleSentence: 'We need to get off at the next stop.' },
  { verb: 'get', particle: 'up', meaningJa: '起きる', exampleSentence: 'I get up at 7 AM every morning.' },
  { verb: 'get', particle: 'along', meaningJa: '仲良くやっていく', exampleSentence: 'Do you get along with your colleagues?' },
  { verb: 'get', particle: 'out', meaningJa: '出て行く、取り出す', exampleSentence: 'Get out of the room.' },
  { verb: 'get', particle: 'in', meaningJa: '到着する、中に入る', exampleSentence: 'What time does the train get in?' },
  { verb: 'get', particle: 'over', meaningJa: '乗り越える、回復する', exampleSentence: 'It took weeks to get over the flu.' },
  { verb: 'get', particle: 'through', meaningJa: 'やり遂げる、連絡がつく', exampleSentence: 'I need to get through this work.' },
  { verb: 'get', particle: 'back', meaningJa: '戻る、取り戻す', exampleSentence: 'When will you get back home?' },
  { verb: 'get', particle: 'away', meaningJa: '逃げる、離れる', exampleSentence: 'We want to get away for the weekend.' },
  { verb: 'get', particle: 'by', meaningJa: 'なんとかやっていく', exampleSentence: 'How do you get by on such a small salary?' },
  { verb: 'get', particle: 'down', meaningJa: '落とす、憂鬱にさせる', exampleSentence: 'This rainy weather gets me down.' },
  { verb: 'turn', particle: 'on', meaningJa: 'つける、起動する', exampleSentence: 'Please turn on the light.' },
  { verb: 'turn', particle: 'off', meaningJa: '消す、停止する', exampleSentence: 'Don\'t forget to turn off the TV.' },
  { verb: 'turn', particle: 'up', meaningJa: '現れる、音量を上げる', exampleSentence: 'He didn\'t turn up for the meeting.' },
  { verb: 'turn', particle: 'down', meaningJa: '断る、音量を下げる', exampleSentence: 'She had to turn down the job offer.' },
  { verb: 'turn', particle: 'out', meaningJa: '判明する、結果になる', exampleSentence: 'Everything turned out fine in the end.' },
  { verb: 'turn', particle: 'over', meaningJa: 'ひっくり返す、引き渡す', exampleSentence: 'Turn the page over.' },
  { verb: 'turn', particle: 'around', meaningJa: '方向転換する、好転させる', exampleSentence: 'We need to turn the business around.' },
  { verb: 'give', particle: 'up', meaningJa: '諦める、やめる', exampleSentence: 'Never give up on your dreams.' },
  { verb: 'give', particle: 'in', meaningJa: '屈する、提出する', exampleSentence: 'He finally gave in to their demands.' },
  { verb: 'give', particle: 'out', meaningJa: '配る、使い果たす', exampleSentence: 'They gave out free samples at the store.' },
  { verb: 'give', particle: 'away', meaningJa: 'タダで譲る、秘密を漏らす', exampleSentence: 'She gave away all her old books.' },
  { verb: 'give', particle: 'back', meaningJa: '返す', exampleSentence: 'Please give me back my pen.' },
  { verb: 'look', particle: 'at', meaningJa: '見る', exampleSentence: 'Look at the beautiful sunset.' },
  { verb: 'look', particle: 'for', meaningJa: '探す', exampleSentence: 'I am looking for my keys.' },
  { verb: 'look', particle: 'after', meaningJa: '世話をする', exampleSentence: 'Can you look after my dog?' },
  { verb: 'look', particle: 'forward', meaningJa: '楽しみに待つ', exampleSentence: 'I look forward to seeing you.' },
  { verb: 'look', particle: 'into', meaningJa: '調査する', exampleSentence: 'The police are looking into the matter.' },
  { verb: 'look', particle: 'out', meaningJa: '気をつける', exampleSentence: 'Look out! A car is coming.' },
  { verb: 'look', particle: 'up', meaningJa: '調べる、見上げる', exampleSentence: 'Look up the word in the dictionary.' },
  { verb: 'look', particle: 'over', meaningJa: '軽く目を通す', exampleSentence: 'Please look over this report.' },
  { verb: 'look', particle: 'down', meaningJa: '見下ろす、軽蔑する', exampleSentence: 'Don\'t look down from the balcony.' },
  { verb: 'come', particle: 'in', meaningJa: '入る', exampleSentence: 'Please come in and make yourself at home.' },
  { verb: 'come', particle: 'out', meaningJa: '出る、出版される', exampleSentence: 'When does their new album come out?' },
  { verb: 'come', particle: 'up', meaningJa: '話題に出る、近づく', exampleSentence: 'An interesting question came up.' },
  { verb: 'come', particle: 'across', meaningJa: '偶然見つける、印象を与える', exampleSentence: 'I came across an old photo.' },
  { verb: 'come', particle: 'back', meaningJa: '戻る', exampleSentence: 'When will you come back?' },
  { verb: 'come', particle: 'from', meaningJa: '出身である', exampleSentence: 'Where do you come from?' },
  { verb: 'come', particle: 'on', meaningJa: 'さあ、急ぐ、始まる', exampleSentence: 'Come on, we are going to be late.' },
  { verb: 'come', particle: 'off', meaningJa: '取れる、はがれる', exampleSentence: 'The button came off my shirt.' },
  { verb: 'come', particle: 'to', meaningJa: '意識を取り戻す、合計になる', exampleSentence: 'The total comes to fifty dollars.' },
  { verb: 'go', particle: 'on', meaningJa: '続く、起こる', exampleSentence: 'What is going on here?' },
  { verb: 'go', particle: 'out', meaningJa: '外出する、消える', exampleSentence: 'Let\'s go out for dinner tonight.' },
  { verb: 'go', particle: 'off', meaningJa: '鳴る、爆発する、腐る', exampleSentence: 'The alarm went off at 6 AM.' },
  { verb: 'go', particle: 'up', meaningJa: '上がる、上昇する', exampleSentence: 'Gas prices have gone up again.' },
  { verb: 'go', particle: 'down', meaningJa: '下がる、沈む', exampleSentence: 'The sun goes down in the west.' },
  { verb: 'go', particle: 'through', meaningJa: '経験する、目を通す', exampleSentence: 'She went through a difficult time.' },
  { verb: 'go', particle: 'back', meaningJa: '戻る', exampleSentence: 'I have to go back to the office.' },
  { verb: 'go', particle: 'along', meaningJa: '賛成する、一緒に行く', exampleSentence: 'I\'ll go along with your plan.' },
  { verb: 'go', particle: 'without', meaningJa: 'なしで済ます', exampleSentence: 'We can\'t go without water.' },
  { verb: 'go', particle: 'over', meaningJa: '確認する、復習する', exampleSentence: 'Let\'s go over the details once more.' },
  { verb: 'put', particle: 'on', meaningJa: '着る、身につける', exampleSentence: 'Put on your coat before you go out.' },
  { verb: 'put', particle: 'off', meaningJa: '延期する', exampleSentence: 'We must put off the meeting until tomorrow.' },
  { verb: 'put', particle: 'up', meaningJa: '建てる、泊める、掲げる', exampleSentence: 'They put up a new building.' },
  { verb: 'put', particle: 'down', meaningJa: '書き留める、下ろす', exampleSentence: 'Please put your name down on this list.' },
  { verb: 'put', particle: 'out', meaningJa: '消す、出す', exampleSentence: 'Firefighters put out the fire.' },
  { verb: 'put', particle: 'back', meaningJa: '元の場所に戻す', exampleSentence: 'Put the book back on the shelf.' },
  { verb: 'put', particle: 'through', meaningJa: '電話をつなぐ、苦しませる', exampleSentence: 'Can you put me through to manager?' },
  { verb: 'put', particle: 'across', meaningJa: 'わかりやすく伝える', exampleSentence: 'He managed to put his idea across.' },
  { verb: 'bring', particle: 'up', meaningJa: '育てる、話題を持ち出す', exampleSentence: 'She was brought up in Tokyo.' },
  { verb: 'bring', particle: 'out', meaningJa: '発売する、引き出す', exampleSentence: 'The company brought out a new smartphone.' },
  { verb: 'bring', particle: 'about', meaningJa: '引き起こす、もたらす', exampleSentence: 'Technology brought about huge changes.' },
  { verb: 'bring', particle: 'back', meaningJa: '思い出させる、持ち帰る', exampleSentence: 'This song brings back memories.' },
  { verb: 'bring', particle: 'down', meaningJa: '下げる、倒す', exampleSentence: 'The government was brought down.' },
  { verb: 'call', particle: 'back', meaningJa: '折り返し電話する', exampleSentence: 'I will call you back later.' },
  { verb: 'call', particle: 'off', meaningJa: '中止する', exampleSentence: 'The match was called off due to rain.' },
  { verb: 'call', particle: 'out', meaningJa: '大声で叫ぶ', exampleSentence: 'He called out my name.' },
  { verb: 'call', particle: 'for', meaningJa: '必要とする、要求する', exampleSentence: 'This situation calls for immediate action.' },
  { verb: 'call', particle: 'on', meaningJa: '訪問する、求める', exampleSentence: 'I will call on my grandparents.' },
  { verb: 'keep', particle: 'on', meaningJa: '続け る', exampleSentence: 'Keep on trying and you will succeed.' },
  { verb: 'keep', particle: 'up', meaningJa: '維持する、遅れずについていく', exampleSentence: 'Keep up the good work.' },
  { verb: 'keep', particle: 'out', meaningJa: '立ち入らない', exampleSentence: 'Keep out of this room.' },
  { verb: 'keep', particle: 'away', meaningJa: '近づかない', exampleSentence: 'Keep away from the edge.' },
  { verb: 'keep', particle: 'back', meaningJa: '抑える、下がらせる', exampleSentence: 'Keep back from the train platform.' },
  { verb: 'keep', particle: 'in', meaningJa: '中に閉じ込めておく、控える', exampleSentence: 'Keep the dog in the yard.' },
  { verb: 'hold', particle: 'on', meaningJa: '待つ、しっかり掴まる', exampleSentence: 'Hold on a moment, please.' },
  { verb: 'hold', particle: 'up', meaningJa: '遅らせる、持ちこたえる', exampleSentence: 'Traffic was held up by an accident.' },
  { verb: 'hold', particle: 'back', meaningJa: '抑える、隠す', exampleSentence: 'She couldn\'t hold back her tears.' },
  { verb: 'hold', particle: 'out', meaningJa: '持ちこたえる、差し出す', exampleSentence: 'How long can they hold out?' },
  { verb: 'run', particle: 'out', meaningJa: '切らす、使い果たす', exampleSentence: 'We have run out of milk.' },
  { verb: 'run', particle: 'into', meaningJa: '偶然出会う、直面する', exampleSentence: 'I ran into an old friend.' },
  { verb: 'run', particle: 'away', meaningJa: '逃げる', exampleSentence: 'The thief ran away from the police.' },
  { verb: 'run', particle: 'over', meaningJa: 'ひく、あふれる', exampleSentence: 'The bathtub is running over.' },
  { verb: 'run', particle: 'through', meaningJa: 'ざっと目を通す、使い果たす', exampleSentence: 'Let\'s run through the script.' },
  { verb: 'set', particle: 'up', meaningJa: '設立する、準備する', exampleSentence: 'They set up a new company.' },
  { verb: 'set', particle: 'out', meaningJa: '出発する、着手する', exampleSentence: 'They set out on a long journey.' },
  { verb: 'set', particle: 'off', meaningJa: '出発する、引き起こす', exampleSentence: 'We set off early in the morning.' },
  { verb: 'set', particle: 'back', meaningJa: '遅らせる、費用がかかる', exampleSentence: 'The project was set back by weeks.' },
  { verb: 'make', particle: 'up', meaningJa: '構成する、化粧する、仲直りする', exampleSentence: 'Women make up half of the workforce.' },
  { verb: 'make', particle: 'out', meaningJa: '聞き取る、理解する', exampleSentence: 'I can\'t make out what he is saying.' },
  { verb: 'make', particle: 'for', meaningJa: '〜に向かう、寄与する', exampleSentence: 'They made for the nearest exit.' },
  { verb: 'make', particle: 'off', meaningJa: '逃げ出す', exampleSentence: 'The burglar made off with the money.' },
  { verb: 'stand', particle: 'up', meaningJa: '立ち上がる', exampleSentence: 'Please stand up when the teacher enters.' },
  { verb: 'stand', particle: 'out', meaningJa: '目立つ', exampleSentence: 'Her bright red dress stood out.' },
  { verb: 'stand', particle: 'for', meaningJa: '表す、意味する、支持する', exampleSentence: 'What does WHO stand for?' },
  { verb: 'stand', particle: 'by', meaningJa: '待機する、支持する', exampleSentence: 'Please stand by for further instructions.' },
  { verb: 'break', particle: 'down', meaningJa: '故障する、精神的に落ち込む', exampleSentence: 'My car broke down on the highway.' },
  { verb: 'break', particle: 'up', meaningJa: '解散する、別れる', exampleSentence: 'They decided to break up.' },
  { verb: 'break', particle: 'out', meaningJa: '勃発する、突然始まる', exampleSentence: 'A fire broke out during the night.' },
  { verb: 'break', particle: 'in', meaningJa: '慣らす、侵入する', exampleSentence: 'I need to break in my new shoes.' },
  { verb: 'break', particle: 'through', meaningJa: '突破する', exampleSentence: 'The sun broke through the clouds.' },
  { verb: 'catch', particle: 'up', meaningJa: '追いつく', exampleSentence: 'Walk slower so I can catch up.' },
  { verb: 'catch', particle: 'on', meaningJa: '人気が出る、理解する', exampleSentence: 'The new fashion quickly caught on.' },
  { verb: 'catch', particle: 'out', meaningJa: '意表をつく、粗を見つける', exampleSentence: 'He was caught out in a lie.' },
  { verb: 'check', particle: 'in', meaningJa: 'チェックインする、手続きをする', exampleSentence: 'We need to check in at the hotel.' },
  { verb: 'check', particle: 'out', meaningJa: 'チェックアウトする、確認する', exampleSentence: 'Check out this cool website.' },
  { verb: 'check', particle: 'up', meaningJa: '調べる、点検する', exampleSentence: 'I want to check up on his progress.' },
  { verb: 'drop', particle: 'out', meaningJa: '中退する、脱落する', exampleSentence: 'He dropped out of university.' },
  { verb: 'drop', particle: 'off', meaningJa: '降ろす、うとうとする', exampleSentence: 'Can you drop me off at the station?' },
  { verb: 'drop', particle: 'in', meaningJa: '立ち寄る', exampleSentence: 'Feel free to drop in anytime.' },
  { verb: 'fall', particle: 'apart', meaningJa: 'バラバラになる、崩壊する', exampleSentence: 'The old book is falling apart.' },
  { verb: 'fall', particle: 'behind', meaningJa: '遅れを取る', exampleSentence: 'Don\'t fall behind in your studies.' },
  { verb: 'fall', particle: 'for', meaningJa: 'だまされる、恋に落ちる', exampleSentence: 'I fell for his trick.' },
  { verb: 'fall', particle: 'out', meaningJa: '喧嘩する、仲たがいする', exampleSentence: 'They fell out over money.' },
  { verb: 'fill', particle: 'out', meaningJa: '記入する', exampleSentence: 'Please fill out this application form.' },
  { verb: 'fill', particle: 'in', meaningJa: '書き込む、穴埋めする', exampleSentence: 'Fill in the blanks with correct words.' },
  { verb: 'fill', particle: 'up', meaningJa: '満たす', exampleSentence: 'Fill up the tank with gas, please.' },
  { verb: 'find', particle: 'out', meaningJa: '見つけ出す、知る', exampleSentence: 'We need to find out the truth.' },
  { verb: 'grow', particle: 'up', meaningJa: '成長する、大人になる', exampleSentence: 'He grew up in a small town.' },
  { verb: 'grow', particle: 'out', meaningJa: '成長して合わなくなる', exampleSentence: 'He grew out of his shoes.' },
  { verb: 'hang', particle: 'up', meaningJa: '電話を切る', exampleSentence: 'Don\'t hang up yet.' },
  { verb: 'hang', particle: 'on', meaningJa: '待つ、しがみつく', exampleSentence: 'Hang on a second.' },
  { verb: 'hang', particle: 'out', meaningJa: 'ぶらつく、遊ぶ', exampleSentence: 'Where do you usually hang out?' },
  { verb: 'hear', particle: 'from', meaningJa: '便りがある、連絡を受ける', exampleSentence: 'I haven\'t heard from him lately.' },
  { verb: 'hear', particle: 'of', meaningJa: '耳にする、知っている', exampleSentence: 'Have you ever heard of this band?' },
  { verb: 'leave', particle: 'out', meaningJa: '省く、除外する', exampleSentence: 'You left out an important detail.' },
  { verb: 'leave', particle: 'behind', meaningJa: '置き忘れる、置いていく', exampleSentence: 'Don\'t leave your umbrella behind.' },
  { verb: 'let', particle: 'down', meaningJa: 'がっかりさせる', exampleSentence: 'I won\'t let you down.' },
  { verb: 'let', particle: 'in', meaningJa: '中に入れる', exampleSentence: 'Open the door and let him in.' },
  { verb: 'let', particle: 'out', meaningJa: '外に出す、もらす', exampleSentence: 'Don\'t let out the secret.' },
  { verb: 'pass', particle: 'away', meaningJa: '亡くなる', exampleSentence: 'His grandfather passed away last year.' },
  { verb: 'pass', particle: 'out', meaningJa: '気絶する、配る', exampleSentence: 'He passed out from the heat.' },
  { verb: 'pass', particle: 'on', meaningJa: '伝える、渡す', exampleSentence: 'Please pass on this message.' },
  { verb: 'pay', particle: 'back', meaningJa: '返す、借金を返済する', exampleSentence: 'I will pay you back tomorrow.' },
  { verb: 'pay', particle: 'attention', meaningJa: '注意を払う', exampleSentence: 'Pay attention to the teacher.' },
  { verb: 'pick', particle: 'up', meaningJa: '拾い上げる、車で迎えに行く', exampleSentence: 'Can you pick me up at the station?' },
  { verb: 'pick', particle: 'out', meaningJa: '選び出す', exampleSentence: 'Pick out the best one.' },
  { verb: 'point', particle: 'out', meaningJa: '指摘する', exampleSentence: 'She pointed out the mistake in the report.' },
  { verb: 'pull', particle: 'out', meaningJa: '引き抜く、車を発進させる', exampleSentence: 'The train is pulling out of the station.' },
  { verb: 'pull', particle: 'through', meaningJa: '切り抜ける、回復する', exampleSentence: 'He managed to pull through the illness.' },
  { verb: 'search', particle: 'for', meaningJa: '探し求める', exampleSentence: 'They are searching for clues.' },
  { verb: 'see', particle: 'off', meaningJa: '見送る', exampleSentence: 'We went to the airport to see him off.' },
  { verb: 'see', particle: 'through', meaningJa: '見抜く、最後までやり通す', exampleSentence: 'I can see through his lies.' },
  { verb: 'show', particle: 'up', meaningJa: '現れる、姿を見せる', exampleSentence: 'He didn\'t show up for the party.' },
  { verb: 'show', particle: 'off', meaningJa: '見せびらかす', exampleSentence: 'He loves to show off his new car.' },
  { verb: 'shut', particle: 'down', meaningJa: '閉鎖する、シャットダウンする', exampleSentence: 'The factory was shut down.' },
  { verb: 'shut', particle: 'up', meaningJa: '黙る、黙らせる', exampleSentence: 'Just shut up and listen.' },
  { verb: 'sit', particle: 'down', meaningJa: '座る', exampleSentence: 'Please sit down.' },
  { verb: 'sleep', particle: 'in', meaningJa: '朝寝坊する', exampleSentence: 'I love to sleep in on weekends.' },
  { verb: 'speak', particle: 'up', meaningJa: 'はっきり話す、意見を言う', exampleSentence: 'Please speak up so everyone can hear.' },
  { verb: 'spend', particle: 'on', meaningJa: '〜にお金を使う', exampleSentence: 'He spends a lot on books.' },
  { verb: 'stay', particle: 'up', meaningJa: '夜更かしする', exampleSentence: 'I stayed up late watching movies.' },
  { verb: 'stay', particle: 'away', meaningJa: '離れている', exampleSentence: 'Stay away from danger.' },
  { verb: 'step', particle: 'down', meaningJa: '辞任する、退く', exampleSentence: 'The CEO decided to step down.' },
  { verb: 'step', particle: 'up', meaningJa: '強化する、進み出る', exampleSentence: 'We need to step up our efforts.' },
  { verb: 'stick', particle: 'to', meaningJa: '固執する、やり通す', exampleSentence: 'Stick to your plan.' },
  { verb: 'stick', particle: 'out', meaningJa: '突き出る、目立つ', exampleSentence: 'His ears stick out slightly.' },
  { verb: 'switch', particle: 'on', meaningJa: 'スイッチを入れる', exampleSentence: 'Switch on the TV.' },
  { verb: 'switch', particle: 'off', meaningJa: 'スイッチを切る', exampleSentence: 'Switch off the lights.' },
  { verb: 'think', particle: 'over', meaningJa: 'じっくり考える', exampleSentence: 'Let me think over your proposal.' },
  { verb: 'think', particle: 'about', meaningJa: '考える', exampleSentence: 'Think about what you did.' },
  { verb: 'throw', particle: 'away', meaningJa: '捨てる', exampleSentence: 'Don\'t throw away this paper.' },
  { verb: 'throw', particle: 'out', meaningJa: '追い出す、捨てる', exampleSentence: 'Throw out the garbage.' },
  { verb: 'try', particle: 'on', meaningJa: '試着する', exampleSentence: 'May I try on this jacket?' },
  { verb: 'try', particle: 'out', meaningJa: '試してみる', exampleSentence: 'Let\'s try out the new software.' },
  { verb: 'wake', particle: 'up', meaningJa: '目が覚める、起こす', exampleSentence: 'Wake me up at 7 o\'clock.' },
  { verb: 'warm', particle: 'up', meaningJa: '暖まる、準備運動する', exampleSentence: 'Warm up before you exercise.' },
  { verb: 'wash', particle: 'up', meaningJa: '皿を洗う、手を洗う', exampleSentence: 'Who is going to wash up after dinner?' },
  { verb: 'wear', particle: 'out', meaningJa: 'すり減らす、疲れ果てさせる', exampleSentence: 'This work wore me out.' },
  { verb: 'work', particle: 'out', meaningJa: '運動する、うまくいくだけでなく解決する', exampleSentence: 'Things will work out in the end.' },
  { verb: 'work', particle: 'on', meaningJa: '取り組む', exampleSentence: 'I am working on a new project.' },
  { verb: 'write', particle: 'down', meaningJa: '書き留める', exampleSentence: 'Write down the address.' },
  { verb: 'zero', particle: 'in', meaningJa: '集中する、照準を合わせる', exampleSentence: 'Zero in on the main problem.' },
];

async function main() {
  console.log('Seeding phrasal verbs...');

  // 既存データを一度すべてクリアして入れ直す場合
  await prisma.phrasalVerb.deleteMany();

  for (const item of phrasalVerbsData) {
    await prisma.phrasalVerb.create({
      data: item,
    });
  }
  console.log('Seeding completed!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });